services:
  postgres:
    image: postgres:15-alpine
    container_name: finance_postgres
    environment:
      POSTGRES_USER: financeuser
      POSTGRES_PASSWORD: financepass
      POSTGRES_DB: financedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U financeuser -d financedb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - finance-network

  api:
    build:
      dockerfile: Dockerfile
    container_name: finance_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: financeuser
      DB_PASSWORD: financepass
      DB_NAME: financedb
      DB_SSLMODE: disable
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - finance-network
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: finance_web
    ports:
      - "3000:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - finance-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  finance-network:
    driver: bridge
